language:  generic

notifications:
  slack:
    rooms:
      - apacheexpress:9z2IfvxZfENp0TFmiYCgyUKz

matrix:
    include:
        - os:   Linux
          dist: trusty
          sudo: required
        - os:   osx
          osx_image: xcode10.0
        - os:   osx
          osx_image: xcode10.2

before_install:
    - ./.travis.d/before-install.sh

script:
    - make all
